# Generated by Django 6.0.6 on 2026-06-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon-Fri', 'Monday - Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Work Hour',
                'verbose_name_plural': 'Work Hours',
                'ordering': ['id'],
            },
        ),
    ]
