# Generated by Django 6.0.6 on 2026-06-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_achievement_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('fa-globe', 'Globe - Web'), ('fa-mobile-alt', 'Mobile'), ('fa-cloud', 'Cloud'), ('fa-robot', 'Robot - AI'), ('fa-shield-alt', 'Shield - Security'), ('fa-chart-line', 'Chart - Marketing'), ('fa-code', 'Code'), ('fa-database', 'Database'), ('fa-brain', 'Brain - AI'), ('fa-laptop-code', 'Laptop Code'), ('fa-shopping-cart', 'Shopping Cart'), ('fa-hospital', 'Hospital'), ('fa-graduation-cap', 'Graduation Cap')], default='fa-globe', max_length=50)),
                ('features', models.JSONField(default=list, help_text="List of features: ['Feature 1', 'Feature 2']")),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=False, help_text='Show this service on home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'id'],
            },
        ),
    ]
