# Generated by Django 6.0.6 on 2026-06-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('fa-globe', 'Globe - Web'), ('fa-mobile-alt', 'Mobile'), ('fa-cloud', 'Cloud'), ('fa-robot', 'Robot - AI'), ('fa-shield-alt', 'Shield - Security'), ('fa-chart-line', 'Chart - Marketing'), ('fa-code', 'Code'), ('fa-database', 'Database'), ('fa-brain', 'Brain - AI'), ('fa-laptop-code', 'Laptop Code'), ('fa-shopping-cart', 'Shopping Cart'), ('fa-hospital', 'Hospital'), ('fa-graduation-cap', 'Graduation Cap'), ('fa-search', 'Search - SEO'), ('fa-magnifying-glass', 'Magnifying Glass - SEO'), ('fa-ranking-star', 'Ranking Star - SEO'), ('fa-youtube', 'YouTube'), ('fa-play-circle', 'Play Circle - Video'), ('fa-video', 'Video Camera'), ('fa-clapperboard', 'Clapperboard - Video'), ('fa-bullhorn', 'Bullhorn - Marketing'), ('fa-megaphone', 'Megaphone - Marketing'), ('fa-ads', 'Ads - Marketing'), ('fa-hashtag', 'Hashtag - Social Media'), ('fa-share-nodes', 'Share Nodes - Social'), ('fa-envelope-open-text', 'Email Marketing'), ('fa-paper-plane', 'Paper Plane - Marketing')], default='fa-globe', max_length=50),
        ),
    ]
