# Generated by Django 6.0.6 on 2026-06-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(default='fa-code', max_length=50)),
                ('duration', models.CharField(help_text='e.g., 12 Weeks', max_length=50)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('schedule', models.CharField(choices=[('Weekends', 'Weekends'), ('Mon-Wed', 'Monday - Wednesday'), ('Thu-Sat', 'Thursday - Saturday'), ('Daily', 'Daily'), ('Flexible', 'Flexible')], default='Weekends', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open for Enrollment'), ('Closed', 'Enrollment Closed'), ('Coming Soon', 'Coming Soon')], default='Open', max_length=20)),
                ('short_description', models.TextField(help_text='Short text for card')),
                ('full_description', models.TextField(help_text='Full details for detail page')),
                ('syllabus', models.JSONField(default=list, help_text="List of topics: ['Topic 1', 'Topic 2']")),
                ('projects', models.JSONField(default=list, help_text="List of projects: ['Project 1', 'Project 2']")),
                ('tools', models.JSONField(default=list, help_text="Tools covered: ['Tool 1', 'Tool 2']")),
                ('start_date', models.DateField(blank=True, null=True)),
                ('fee', models.CharField(blank=True, help_text='e.g., PKR 15,000', max_length=50, null=True)),
                ('instructor', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=False, help_text='Show on home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['order', 'id'],
            },
        ),
    ]
