# Generated by Django 6.0.6 on 2026-06-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='Main Ghala Mandi Road, Rajanpur, Punjab, Pakistan')),
                ('phone', models.CharField(default='+92 300 1234567', max_length=50)),
                ('email', models.EmailField(default='info@digitalking.com.pk', max_length=254)),
                ('whatsapp', models.CharField(blank=True, default='+92 300 1234567', max_length=50, null=True)),
                ('map_embed_url', models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d215527.47870880097!2d70.123456!3d29.123456!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3938f5c6a5b8b8b9%3A0x8b8b8b8b8b8b8b8b!2sRajanpur!5e0!3m2!1sen!2s!4v1700000000000!5m2!1sen!2s', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('url', models.URLField()),
                ('icon', models.CharField(default='fa-facebook-f', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.CharField(choices=[('fa-globe', 'Globe - Web'), ('fa-mobile-alt', 'Mobile'), ('fa-cloud', 'Cloud'), ('fa-robot', 'Robot - AI'), ('fa-shield-alt', 'Shield - Security'), ('fa-chart-line', 'Chart - Marketing'), ('fa-code', 'Code'), ('fa-database', 'Database'), ('fa-brain', 'Brain - AI'), ('fa-laptop-code', 'Laptop Code'), ('fa-shopping-cart', 'Shopping Cart'), ('fa-hospital', 'Hospital'), ('fa-graduation-cap', 'Graduation Cap'), ('fa-search', 'Search - SEO'), ('fa-magnifying-glass', 'Magnifying Glass - SEO'), ('fa-ranking-star', 'Ranking Star - SEO'), ('fa-youtube', 'YouTube'), ('fa-play-circle', 'Play Circle - Video'), ('fa-video', 'Video Camera'), ('fa-clapperboard', 'Clapperboard - Video'), ('fa-bullhorn', 'Bullhorn - Marketing'), ('fa-megaphone', 'Megaphone - Marketing'), ('fa-ads', 'Ads - Marketing'), ('fa-hashtag', 'Hashtag - Social Media'), ('fa-share-nodes', 'Share Nodes - Social'), ('fa-envelope-open-text', 'Email Marketing'), ('fa-paper-plane', 'Paper Plane - Marketing')], default='fa-code', max_length=50),
        ),
    ]
