# Generated by Django 6.0.6 on 2026-06-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projectcategory_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=20)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('icon', models.CharField(default='fa-check', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Stat',
                'verbose_name_plural': 'Site Stats',
                'ordering': ['order'],
            },
        ),
    ]
