# Generated by Django 6.0.6 on 2026-06-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sitestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(default='General', max_length=50)),
                ('excerpt', models.TextField(help_text='Short summary for card view')),
                ('content', models.TextField(help_text='Full blog post content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.CharField(default='Digital King Team', max_length=100)),
                ('published_date', models.DateField()),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Estimated read time in minutes')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on home page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
